/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sdCAnvguKZQ
 */
import Link from "next/link"

export function Navbar() {
  return (
    <nav className="flex flex-row items-center h-16 px-4 border-b border-gray-200/50 backdrop-filter backdrop-blur-sm/tint-10 fixed inset-x-0 top-0 z-50 justify-between bg-gray-950 dark:bg-gray-50/60 border-gray-200 dark:border-gray-800">
      <div className="flex items-center space-x-4">
        {/* <Button>Button 1</Button>
        <Button>Button 2</Button> */}
      </div>
      <Link className="flex items-center" href="#">
        <FlagIcon className="h-6 w-6" />
        <span className="ml-2 font-medium sm:hidden">Acme Inc</span>
      </Link>
      <nav className="flex items-center space-x-4">
        <Link className="font-medium" href="#">
          Home
        </Link>
        <Link className="font-medium" href="#">
          About
        </Link>
        <Link className="font-medium" href="#">
          Services
        </Link>
        <Link className="font-medium" href="#">
          Contact
        </Link>
      </nav>
    </nav>
  )
}


function FlagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}
